
-- Create Upvotes Table
create table if not exists public.post_upvotes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  fingerprint text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (post_id, fingerprint)
);

-- Enable RLS
alter table public.post_upvotes enable row level security;

-- Policies
create policy "Public can read upvotes"
  on public.post_upvotes for select
  using (true);

create policy "Public can vote"
  on public.post_upvotes for insert
  with check (true);

create policy "Public can unvote"
  on public.post_upvotes for delete
  using (true);

-- RPC Function for Atomic Toggle
create or replace function toggle_vote(
  post_id_input bigint,
  fingerprint_input text
) returns json
language plpgsql
security definer
as $$
declare
  existing_vote_id bigint;
  new_count bigint;
  has_voted boolean;
begin
  -- Check for existing vote
  select id into existing_vote_id
  from public.post_upvotes
  where post_id = post_id_input and fingerprint = fingerprint_input;

  if existing_vote_id is not null then
    -- DELETE vote
    delete from public.post_upvotes where id = existing_vote_id;
    has_voted := false;
  else
    -- INSERT vote
    insert into public.post_upvotes (post_id, fingerprint)
    values (post_id_input, fingerprint_input);
    has_voted := true;
  end if;

  -- Get updated count
  select count(*) into new_count
  from public.post_upvotes
  where post_id = post_id_input;

  return json_build_object(
    'has_voted', has_voted,
    'count', new_count
  );
end;
$$;
