-- v37 FINAL PROVEN FIX (Bundles everything)
-- Use this to fix "Function Not Found" and "Ambiguous Column" errors once and for all.

-- 1. CLEANUP (Drop potentially conflicting old functions)
DROP FUNCTION IF EXISTS public.get_dashboard_stats(uuid);
DROP FUNCTION IF EXISTS public.increment_post_view(bigint);
DROP FUNCTION IF EXISTS public.increment_shares(bigint);
DROP FUNCTION IF EXISTS public.count_post_visit(bigint);
DROP FUNCTION IF EXISTS public.count_post_action(bigint);

-- 2. CREATE EVENT TABLE (The "Log" Approach)
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id bigint generated by default as identity primary key,
    post_id bigint references public.posts(id) on delete cascade not null,
    type text not null check (type in ('view', 'share')),
    created_at timestamptz default now()
);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can log events" ON public.analytics_events;
CREATE POLICY "Public can log events" ON public.analytics_events FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admins can view events" ON public.analytics_events;
CREATE POLICY "Admins can view events" ON public.analytics_events FOR SELECT USING (true);

-- 3. CREATE TRIGGER (The "Processor")
CREATE OR REPLACE FUNCTION public.process_analytics_event()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.type = 'view' THEN
        UPDATE public.posts SET views = coalesce(views, 0) + 1 WHERE id = NEW.post_id;
        INSERT INTO public.daily_post_stats (date, post_id, views) 
        VALUES (CURRENT_DATE, NEW.post_id, 1) 
        ON CONFLICT (date, post_id) DO UPDATE SET views = daily_post_stats.views + 1;
    ELSIF NEW.type = 'share' THEN
        UPDATE public.posts SET shares = coalesce(shares, 0) + 1 WHERE id = NEW.post_id;
        INSERT INTO public.daily_post_stats (date, post_id, shares) 
        VALUES (CURRENT_DATE, NEW.post_id, 1) 
        ON CONFLICT (date, post_id) DO UPDATE SET shares = daily_post_stats.shares + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_analytics_event ON public.analytics_events;
CREATE TRIGGER on_analytics_event AFTER INSERT ON public.analytics_events
FOR EACH ROW EXECUTE FUNCTION public.process_analytics_event();

-- 4. CREATE WRITER FUNCTIONS (RPCs called by Blog.tsx)
CREATE OR REPLACE FUNCTION public.log_view(p_post_id bigint) RETURNS void AS $$
BEGIN
    INSERT INTO public.analytics_events (post_id, type) VALUES (p_post_id, 'view');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.log_share(p_post_id bigint) RETURNS void AS $$
BEGIN
    INSERT INTO public.analytics_events (post_id, type) VALUES (p_post_id, 'share');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. CREATE READER FUNCTION (RPC called by Dashboard.tsx)
-- Named 'get_author_overview' to match v34 code
CREATE OR REPLACE FUNCTION public.get_author_overview(p_user_id uuid)
RETURNS json AS $$
declare
  total_views bigint; total_shares bigint; total_subscribers bigint; graph_data json;
begin
  select coalesce(sum(views), 0) into total_views from public.posts where user_id = p_user_id;
  select coalesce(sum(shares), 0) into total_shares from public.posts where user_id = p_user_id;
  select count(*) into total_subscribers from public.subscribers s join public.site_settings ss on s.blog_id = ss.id where ss.user_id = p_user_id;
  
  with recursive dates as (
      select (now() at time zone 'utc')::date - 6 as day
      union all select day + 1 from dates where day < (now() at time zone 'utc')::date
  ),
  daily_agg as (
      select d.date as day, sum(d.views) as views_count, sum(d.shares) as shares_count
      from public.daily_post_stats d join public.posts p on d.post_id = p.id
      where p.user_id = p_user_id and d.date >= (CURRENT_DATE - 6) group by 1
  )
  select json_agg(json_build_object(
      'date', to_char(dt.day, 'YYYY-MM-DD'), 'name', to_char(dt.day, 'Mon DD'),
      'views', coalesce(da.views_count, 0), 'shares', coalesce(da.shares_count, 0)
  ) order by dt.day) into graph_data from dates dt left join daily_agg da on dt.day = da.day;

  return json_build_object('totalViews', total_views, 'totalShares', total_shares, 'totalSubscribers', total_subscribers, 'graphData', coalesce(graph_data, '[]'::json));
end;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. GRANT ALL
GRANT EXECUTE ON FUNCTION public.log_view(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.log_share(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_author_overview(uuid) TO anon, authenticated, service_role;
GRANT ALL ON public.analytics_events TO anon, authenticated, service_role;
