-- v40 GUARANTEED FIX
-- Simplified, Monolithic, Robust.

-- 1. CLEAN SLATE (Drop all previous attempts)
DROP FUNCTION IF EXISTS public.get_dashboard_stats(uuid);
DROP FUNCTION IF EXISTS public.get_author_overview(uuid);
DROP FUNCTION IF EXISTS public.increment_post_view(bigint);
DROP FUNCTION IF EXISTS public.increment_shares(bigint);
DROP FUNCTION IF EXISTS public.count_post_visit(bigint);
DROP FUNCTION IF EXISTS public.count_post_action(bigint);
DROP FUNCTION IF EXISTS public.log_view(bigint);
DROP FUNCTION IF EXISTS public.log_share(bigint);
DROP TRIGGER IF EXISTS on_analytics_event ON public.analytics_events;

-- 2. ENSURE TABLES EXIST
CREATE TABLE IF NOT EXISTS public.daily_post_stats (
    id bigint generated by default as identity primary key,
    post_id bigint references public.posts(id) on delete cascade not null,
    date date not null default current_date,
    views bigint default 0,
    shares bigint default 0,
    unique(date, post_id)
);

ALTER TABLE public.daily_post_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "System full access" ON public.daily_post_stats;
CREATE POLICY "System full access" ON public.daily_post_stats FOR ALL USING (true);


-- 3. THE " ONE FUNCTION TO RULE THEM ALL " (Writer)
-- Handles both Views and Shares. Updates both Totals and Daily.
CREATE OR REPLACE FUNCTION public.track_event(p_post_id bigint, p_type text)
RETURNS void AS $$
BEGIN
    IF p_type = 'view' THEN
        -- Update Total
        UPDATE public.posts 
        SET views = coalesce(views, 0) + 1 
        WHERE id = p_post_id;
        
        -- Update Daily
        INSERT INTO public.daily_post_stats (date, post_id, views)
        VALUES (CURRENT_DATE, p_post_id, 1)
        ON CONFLICT (date, post_id) DO UPDATE SET views = daily_post_stats.views + 1;
        
    ELSIF p_type = 'share' THEN
        -- Update Total
        UPDATE public.posts 
        SET shares = coalesce(shares, 0) + 1 
        WHERE id = p_post_id;
        
        -- Update Daily
        INSERT INTO public.daily_post_stats (date, post_id, shares)
        VALUES (CURRENT_DATE, p_post_id, 1)
        ON CONFLICT (date, post_id) DO UPDATE SET shares = daily_post_stats.shares + 1;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 4. THE READER FUNCTION (Dashboard)
CREATE OR REPLACE FUNCTION public.get_basic_stats(p_user_id uuid)
RETURNS json AS $$
declare
  total_views bigint; 
  total_shares bigint; 
  total_subscribers bigint; 
  graph_data json;
begin
  -- Simple Sums
  select coalesce(sum(views), 0) into total_views from public.posts where user_id = p_user_id;
  select coalesce(sum(shares), 0) into total_shares from public.posts where user_id = p_user_id;
  
  -- Subscribers
  select count(*) into total_subscribers 
  from public.subscribers s 
  join public.site_settings ss on s.blog_id = ss.id 
  where ss.user_id = p_user_id;
  
  -- Graph Data (Last 7 Days)
  with recursive dates as (
      select (now() at time zone 'utc')::date - 6 as day
      union all select day + 1 from dates where day < (now() at time zone 'utc')::date
  ),
  daily_agg as (
      select d.date as day, sum(d.views) as views_count, sum(d.shares) as shares_count
      from public.daily_post_stats d join public.posts p on d.post_id = p.id
      where p.user_id = p_user_id and d.date >= (CURRENT_DATE - 6) group by 1
  )
  select json_agg(json_build_object(
      'date', to_char(dt.day, 'YYYY-MM-DD'), 'name', to_char(dt.day, 'Mon DD'),
      'views', coalesce(da.views_count, 0), 'shares', coalesce(da.shares_count, 0)
  ) order by dt.day) into graph_data from dates dt left join daily_agg da on dt.day = da.day;

  return json_build_object(
    'totalViews', total_views, 
    'totalShares', total_shares, 
    'totalSubscribers', total_subscribers, 
    'graphData', coalesce(graph_data, '[]'::json)
  );
end;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. GRANT PERMISSIONS (OPEN TO ALL)
GRANT EXECUTE ON FUNCTION public.track_event(bigint, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_basic_stats(uuid) TO anon, authenticated, service_role;
