-- v45 GRAPH FIX (DISABLE RLS ON DAILY STATS)
-- To allow the client to directly update graph data.

-- 1. Ensure Table Exists
CREATE TABLE IF NOT EXISTS public.daily_post_stats (
    id bigint generated by default as identity primary key,
    post_id bigint references public.posts(id) on delete cascade not null,
    date date not null default current_date,
    views bigint default 0,
    shares bigint default 0,
    unique(date, post_id)
);

-- 2. DISABLE SECURITY (Allows Direct Client Updates)
ALTER TABLE public.daily_post_stats DISABLE ROW LEVEL SECURITY;

-- 3. Grant Permissions
GRANT ALL ON public.daily_post_stats TO anon, authenticated, service_role;
