CREATE TABLE IF NOT EXISTS public.daily_post_stats (
    id bigint generated by default as identity primary key,
    post_id bigint references public.posts(id) on delete cascade not null,
    date date not null default current_date,
    views bigint default 0,
    shares bigint default 0,
    unique(date, post_id)
);
ALTER TABLE public.daily_post_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read access" ON public.daily_post_stats;
CREATE POLICY "Public read access" ON public.daily_post_stats FOR SELECT USING (true);
DROP POLICY IF EXISTS "Service role write access" ON public.daily_post_stats;
CREATE POLICY "Service role write access" ON public.daily_post_stats FOR ALL USING (true) WITH CHECK (true);
CREATE TABLE IF NOT EXISTS public.site_settings (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null unique,
    site_name text,
    site_description text,
    subdomain text unique,
    custom_domain text unique,
    created_at timestamptz default now()
);
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.site_settings TO service_role;
GRANT SELECT ON public.site_settings TO anon, authenticated;
