-- HIGH SCALE ARCHITECTURE SCHEMA
-- Run this in Supabase SQL Editor

-- 1. Update Posts Table (if columns don't exist)
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS views BIGINT DEFAULT 0;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS likes BIGINT DEFAULT 0;

-- 2. Create Subscribers Table (if not exists, with Verified flag)
CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Telemetry Daily Table (Aggregated Data)
CREATE TABLE IF NOT EXISTS public.telemetry_daily (
  post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE,
  event TEXT NOT NULL,
  count BIGINT DEFAULT 0,
  day DATE DEFAULT CURRENT_DATE,
  PRIMARY KEY (post_id, event, day)
);

-- 4. Enable RLS
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_daily ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- Public can subscribe (insert)
DROP POLICY IF EXISTS "Public can subscribe" ON public.subscribers;
CREATE POLICY "Public can subscribe" ON public.subscribers FOR INSERT WITH CHECK (true);

-- Admins can view subscribers
DROP POLICY IF EXISTS "Admins can view subscribers" ON public.subscribers;
CREATE POLICY "Admins can view subscribers" ON public.subscribers FOR SELECT USING (auth.uid() IN (SELECT id FROM auth.users));

-- Telemetry is internal/admin only
DROP POLICY IF EXISTS "Admins view telemetry" ON public.telemetry_daily;
CREATE POLICY "Admins view telemetry" ON public.telemetry_daily FOR SELECT USING (auth.uid() IN (SELECT id FROM auth.users));
