-- v36 EVENT ANALYTICS SYSTEM
-- "The Reddit Fix": Use an append-only log + triggers to avoid locking/permission issues.

-- 1. Create the Event Log Table (Append Only)
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id bigint generated by default as identity primary key,
    post_id bigint references public.posts(id) on delete cascade not null,
    type text not null check (type in ('view', 'share')),
    created_at timestamptz default now()
);

-- 2. Open Permissions (Append is safe)
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can log events" ON public.analytics_events;
CREATE POLICY "Public can log events" ON public.analytics_events
FOR INSERT WITH CHECK (true); -- Allow ANYONE to insert (Anon views)

DROP POLICY IF EXISTS "Admins can view events" ON public.analytics_events;
CREATE POLICY "Admins can view events" ON public.analytics_events
FOR SELECT USING (true);

-- 3. Create the Trigger Function (The Brain)
CREATE OR REPLACE FUNCTION public.process_analytics_event()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.type = 'view' THEN
        -- Update Total
        UPDATE public.posts 
        SET views = coalesce(views, 0) + 1 
        WHERE id = NEW.post_id;
        
        -- Update Daily Graph
        INSERT INTO public.daily_post_stats (date, post_id, views)
        VALUES (CURRENT_DATE, NEW.post_id, 1)
        ON CONFLICT (date, post_id) DO UPDATE SET views = daily_post_stats.views + 1;
        
    ELSIF NEW.type = 'share' THEN
        -- Update Total
        UPDATE public.posts 
        SET shares = coalesce(shares, 0) + 1 
        WHERE id = NEW.post_id;
        
        -- Update Daily Graph
        INSERT INTO public.daily_post_stats (date, post_id, shares)
        VALUES (CURRENT_DATE, NEW.post_id, 1)
        ON CONFLICT (date, post_id) DO UPDATE SET shares = daily_post_stats.shares + 1;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER; -- Runs as Admin, bypasses RLS on posts table

-- 4. Attach Trigger
DROP TRIGGER IF EXISTS on_analytics_event ON public.analytics_events;
CREATE TRIGGER on_analytics_event
AFTER INSERT ON public.analytics_events
FOR EACH ROW EXECUTE FUNCTION public.process_analytics_event();

-- 5. Create Simple RPCs (Wrappers)
-- These just insert into the event table. Simple. Hard to break.

CREATE OR REPLACE FUNCTION public.log_view(p_post_id bigint)
RETURNS void AS $$
BEGIN
    INSERT INTO public.analytics_events (post_id, type) VALUES (p_post_id, 'view');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.log_share(p_post_id bigint)
RETURNS void AS $$
BEGIN
    INSERT INTO public.analytics_events (post_id, type) VALUES (p_post_id, 'share');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Grant Access
GRANT EXECUTE ON FUNCTION public.log_view(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.log_share(bigint) TO anon, authenticated, service_role;
GRANT ALL ON public.analytics_events TO anon, authenticated, service_role;
