-- v42 SANITY CHECK (DISABLE SECURITY)
-- Per user request: Turn off RLS to guarantee direct writes work.

-- 1. Ensure Tables Exist
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Keeping BIGINT to match existing schema
  title TEXT,
  views BIGINT DEFAULT 0,
  shares BIGINT DEFAULT 0,
  user_id UUID REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT
);

-- 2. DISABLE RLS (The "Nuclear" Option)
-- This allows ANYONE with the Anon Key to SELECT, INSERT, UPDATE, DELETE rows.
ALTER TABLE public.posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers DISABLE ROW LEVEL SECURITY;

-- 3. Grant Permissions just in case
GRANT ALL ON public.posts TO anon, authenticated, service_role;
GRANT ALL ON public.subscribers TO anon, authenticated, service_role;
