-- v60: Ensure Daily Stats Table Schema
-- PROPERLY DEFINED with ID and constraints to prevent duplicates

CREATE TABLE IF NOT EXISTS public.daily_post_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  views BIGINT DEFAULT 0,
  shares BIGINT DEFAULT 0,
  UNIQUE(post_id, date)
);

-- Ensure RLS is OFF (Nuclear option as per previous fixes)
ALTER TABLE public.daily_post_stats DISABLE ROW LEVEL SECURITY;
GRANT ALL ON public.daily_post_stats TO anon, authenticated, service_role;
