create table if not exists public.post_views (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  
  user_id uuid references auth.users(id) on delete cascade,   -- Nullable (logged in)
  viewer_hash text,                                           -- Nullable (guest)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Constraint: Unique User View
  constraint unique_user_view unique (post_id, user_id),
  
  -- Constraint: Unique Guest View
  constraint unique_guest_view unique (post_id, viewer_hash)
);

-- RLS
alter table public.post_views enable row level security;

-- Policy: Allow service role full access
create policy "Allow service role to manage post_views"
  on public.post_views
  for all
  to service_role
  using (true)
  with check (true);

-- Policy: Allow public read? Probably not needed, just for analytics.
create policy "Allow public read access to post_views"
  on public.post_views
  for select
  using (true);


-- 2. Add views_count cache column (or ensure it exists)
-- Earlier `view_tracking.sql` added `views` column.
-- User prompt Step 1.1 uses `views_count`.
-- I should check if `views` exists and rename/use it, or add `views_count`.
-- `view_tracking.sql` did: `alter table public.posts add column if not exists views bigint default 0;`
-- I will use `views_count` to match the prompt's naming convention for the new "Correct" system, 
-- OR use `views` if I want to keep existing dashboard working without changes.
-- Dashboard uses `sum(views)`.
-- I will use `views` column but aliases it conceptually. Or just use `views` in the name.
-- Prompt Step 2.1: `UPDATE posts SET views_count`.
-- I will stick to `views` column name to avoid breaking Dashboard stats which queries `views`.
-- "return json_build_object(..., 'totalViews', total_views, ...)" depends on `views`.
-- So I will target `views` column.

alter table public.posts 
add column if not exists views bigint default 0;

-- 3. Atomic Increment Function
create or replace function public.increment_views(pid bigint)
returns void as $$
begin
  update public.posts
  set views = views + 1
  where id = pid;
end;
$$ language plpgsql security definer;
