create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade, 
  viewer_hash text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (post_id, user_id),
  unique (post_id, viewer_hash)
);
alter table public.post_likes enable row level security;
create policy "Allow public read access to post_likes"
  on public.post_likes
  for select
  using (true);
alter table public.posts 
add column if not exists likes_count bigint default 0;
create or replace function public.increment_likes(pid bigint)
returns void as $$
begin
  update public.posts
  set likes_count = likes_count + 1
  where id = pid;
end;
$$ language plpgsql security definer;
create or replace function public.decrement_likes(pid bigint)
returns void as $$
begin
  update public.posts
  set likes_count = greatest(likes_count - 1, 0)
  where id = pid;
end;
$$ language plpgsql security definer;
