create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.subscribers enable row level security;
create policy "Public can subscribe"
  on public.subscribers for insert
  with check (true);
create policy "Admins can view subscribers"
  on public.subscribers for select
  using ( auth.uid() in ( select id from auth.users ) ); 
