CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  title TEXT,
  views BIGINT DEFAULT 0,
  shares BIGINT DEFAULT 0,
  user_id UUID REFERENCES auth.users(id)
);
CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT
);
ALTER TABLE public.posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers DISABLE ROW LEVEL SECURITY;
GRANT ALL ON public.posts TO anon, authenticated, service_role;
GRANT ALL ON public.subscribers TO anon, authenticated, service_role;
