CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL UNIQUE,
    site_name TEXT,
    site_description TEXT,
    custom_domain TEXT UNIQUE,
    subdomain TEXT UNIQUE,
    twitter_link TEXT,
    linkedin_link TEXT,
    github_link TEXT,
    website_link TEXT,
    newsletter_email TEXT,
    domain_status TEXT DEFAULT 'pending', 
    verify_token TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own settings" ON public.site_settings;
DROP POLICY IF EXISTS "Users can update their own settings" ON public.site_settings;
DROP POLICY IF EXISTS "Users can insert their own settings" ON public.site_settings;
DROP POLICY IF EXISTS "Public can view settings by custom domain" ON public.site_settings;
DROP POLICY IF EXISTS "Public can view settings by subdomain" ON public.site_settings;
CREATE POLICY "Users can view their own settings"
ON public.site_settings FOR SELECT
USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own settings"
ON public.site_settings FOR UPDATE
USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own settings"
ON public.site_settings FOR INSERT
WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Public can view settings by custom domain" 
ON public.site_settings FOR SELECT 
USING (custom_domain IS NOT NULL);
CREATE POLICY "Public can view settings by subdomain" 
ON public.site_settings FOR SELECT 
USING (subdomain IS NOT NULL);
GRANT ALL ON public.site_settings TO authenticated;
GRANT ALL ON public.site_settings TO service_role;
GRANT SELECT ON public.site_settings TO anon; 
