create table if not exists public.blog_views (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  viewer_hash text not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (post_id, viewer_hash)
);
alter table public.blog_views enable row level security;
create policy "Allow public insert to blog_views"
  on public.blog_views
  for insert
  with check (true);
create policy "Allow public read access to blog_views"
  on public.blog_views
  for select
  using (true);
alter table public.posts 
add column if not exists views bigint default 0;
create or replace function public.increment_post_views()
returns trigger as $$
begin
  update public.posts
  set views = views + 1
  where id = new.post_id;
  return new;
end;
$$ language plpgsql security definer;
drop trigger if exists on_blog_view_added on public.blog_views;
create trigger on_blog_view_added
  after insert on public.blog_views
  for each row
  execute function public.increment_post_views();
