create table if not exists public.post_views (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade,   
  viewer_hash text,                                           
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_user_view unique (post_id, user_id),
  constraint unique_guest_view unique (post_id, viewer_hash)
);
alter table public.post_views enable row level security;
create policy "Allow service role to manage post_views"
  on public.post_views
  for all
  to service_role
  using (true)
  with check (true);
create policy "Allow public read access to post_views"
  on public.post_views
  for select
  using (true);
alter table public.posts 
add column if not exists views bigint default 0;
create or replace function public.increment_views(pid bigint)
returns void as $$
begin
  update public.posts
  set views = views + 1
  where id = pid;
end;
$$ language plpgsql security definer;
